// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package app_test

import (
	"context"
	"sync"
	"theskyinflames/core-tech/listener/internal/app"
)

// Ensure, that MessageHandlerMock does implement app.MessageHandler.
// If this is not the case, regenerate this file with moq.
var _ app.MessageHandler = &MessageHandlerMock{}

// MessageHandlerMock is a mock implementation of app.MessageHandler.
//
//	func TestSomethingThatUsesMessageHandler(t *testing.T) {
//
//		// make and configure a mocked app.MessageHandler
//		mockedMessageHandler := &MessageHandlerMock{
//			HandleFunc: func(ctx context.Context, msg string) error {
//				panic("mock out the Handle method")
//			},
//		}
//
//		// use mockedMessageHandler in code that requires app.MessageHandler
//		// and then make assertions.
//
//	}
type MessageHandlerMock struct {
	// HandleFunc mocks the Handle method.
	HandleFunc func(ctx context.Context, msg string) error

	// calls tracks calls to the methods.
	calls struct {
		// Handle holds details about calls to the Handle method.
		Handle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg string
		}
	}
	lockHandle sync.RWMutex
}

// Handle calls HandleFunc.
func (mock *MessageHandlerMock) Handle(ctx context.Context, msg string) error {
	callInfo := struct {
		Ctx context.Context
		Msg string
	}{
		Ctx: ctx,
		Msg: msg,
	}
	mock.lockHandle.Lock()
	mock.calls.Handle = append(mock.calls.Handle, callInfo)
	mock.lockHandle.Unlock()
	if mock.HandleFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.HandleFunc(ctx, msg)
}

// HandleCalls gets all the calls that were made to Handle.
// Check the length with:
//
//	len(mockedMessageHandler.HandleCalls())
func (mock *MessageHandlerMock) HandleCalls() []struct {
	Ctx context.Context
	Msg string
} {
	var calls []struct {
		Ctx context.Context
		Msg string
	}
	mock.lockHandle.RLock()
	calls = mock.calls.Handle
	mock.lockHandle.RUnlock()
	return calls
}
